# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='usage'),
        ),
    ]
