# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20160412_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_extensions.db.fields.UUIDField(blank=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('owner', models.CharField(blank=True, max_length=200, null=True, verbose_name='owner')),
                ('source', models.TextField(blank=True, null=True, verbose_name='source')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copyrights', to='museum.License')),
            ],
            options={
                'ordering': ('-source',),
                'db_table': 'museum_copyright',
                'verbose_name': 'copyright',
                'verbose_name_plural': 'copyrights',
            },
        ),
        migrations.RemoveField(
            model_name='museumsresource',
            name='license',
        ),
        migrations.AddField(
            model_name='museumsresource',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='museumsresource',
            name='copyright',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='museums_resources', to='museum.Copyright'),
        ),
    ]
