# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 13:34
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20160412_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumsresource',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
