# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumsresource',
            name='link',
            field=models.ManyToManyField(blank=True, related_name='museums_resources', to='museum.Link'),
        ),
    ]
