# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 14:08
from __future__ import unicode_literals

import common.storage
from django.db import migrations, models
import museum.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_auto_20160510_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('first_name',), 'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'diagram', 'verbose_name_plural': 'diagrams'},
        ),
        migrations.AddField(
            model_name='author',
            name='remote_href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_href'),
        ),
        migrations.AddField(
            model_name='author',
            name='remote_uuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_uuid'),
        ),
        migrations.AddField(
            model_name='entry',
            name='remote_href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_href'),
        ),
        migrations.AddField(
            model_name='entry',
            name='remote_uuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_uuid'),
        ),
        migrations.AddField(
            model_name='license',
            name='remote_href',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_href'),
        ),
        migrations.AddField(
            model_name='license',
            name='remote_uuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_uuid'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=common.storage.DataStorage(base_url=b'/media/diagrams/', location=b'/home/stahl/icst/soundcolourspace/sound-colour-space/website/media/diagrams'), upload_to=museum.models.generate_data_path, verbose_name='image'),
        ),
    ]
