# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_auto_20160906_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='license',
        ),
        migrations.AddField(
            model_name='entry',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='museums_entries', to='museum.License'),
        ),
    ]
