# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_auto_20160906_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='museums_entries', to='museum.Author'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='license',
        ),
        migrations.AddField(
            model_name='entry',
            name='license',
            field=models.ManyToManyField(blank=True, related_name='museums_entries', to='museum.License'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='source',
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.ManyToManyField(blank=True, related_name='museums_entries', to='museum.Source'),
        ),
    ]
