# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_auto_20160906_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='owner',
        ),
        migrations.AddField(
            model_name='source',
            name='copyright_notice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='copyright_notice'),
        ),
    ]
