# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0012_auto_20160906_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='copyright_notice',
            field=models.TextField(blank=True, null=True, verbose_name='copyright_notice'),
        ),
    ]
