# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0013_auto_20160906_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='copyright_notice',
            field=models.TextField(blank=True, null=True, verbose_name='copyright_notice'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='source',
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='source'),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
