# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 20:27
from __future__ import unicode_literals

import common.storage
from django.db import migrations, models
import museum.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0014_auto_20160906_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, storage=common.storage.DataStorage(base_url=b'/media/diagrams/', location=b'/home/stahl/icst/soundcolourspace/sound-colour-space/website/media/diagrams'), upload_to=museum.models.generate_data_path, verbose_name='image'),
        ),
    ]
