# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0015_auto_20160910_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='related',
            field=models.ManyToManyField(related_name='_entry_related_+', to='museum.Entry'),
        ),
    ]
