# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0016_entry_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'created', 'ordering': ('title',), 'verbose_name': 'diagram', 'verbose_name_plural': 'diagrams'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, related_name='_entry_related_+', to='museum.Entry'),
        ),
    ]
