# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0017_auto_20160919_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_entry_related_+', to='museum.Entry'),
        ),
    ]
