# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0018_auto_20160919_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='year',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='entry',
            name='date_accuracy',
            field=models.IntegerField(blank=True, choices=[(1, 'exact'), (2, 'month'), (3, 'year'), (4, 'decennium'), (5, 'century'), (6, 'unknown')], default=3, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='portrayed_object_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='portrayed_object_date'),
        ),
    ]
