# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0020_auto_20160923_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
