# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0021_auto_20160928_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='doc_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
