# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0023_auto_20161024_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', django_extensions.db.fields.UUIDField(blank=True, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('remote_uuid', models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_uuid')),
                ('remote_href', models.CharField(blank=True, max_length=200, null=True, verbose_name='remote_href')),
                ('author', models.ManyToManyField(blank=True, related_name='museums_collections', to='museum.Author')),
                ('entry', models.ManyToManyField(blank=True, related_name='museums_collections', to='museum.Entry')),
            ],
            options={
                'db_table': 'museum_collection',
                'verbose_name': 'Diagram Set',
                'verbose_name_plural': 'Diagram Sets',
            },
        ),
    ]
