# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0024_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Set', 'verbose_name_plural': 'Sets'},
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='slug'),
        ),
    ]
