# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-25 15:54
from __future__ import unicode_literals

import common.storage
from django.db import migrations, models
import museum.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0025_auto_20161024_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('title',), 'verbose_name': 'Set', 'verbose_name_plural': 'Sets'},
        ),
        migrations.AddField(
            model_name='experiment',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=common.storage.DataStorage(base_url=b'/media/experiments/', location=b'/home/stahl/icst/soundcolourspace/sound-colour-space/website/media/experiments'), upload_to=museum.models.generate_data_path, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
