# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0026_auto_20161025_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='doc_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
