# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 17:41
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0032_auto_20161104_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='museum.TaggedObject', to='museum.Keyword', verbose_name='Tags'),
        ),
    ]
