# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0033_collection_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('title',), 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'keyword', 'verbose_name_plural': 'keywords'},
        ),
    ]
