# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0034_auto_20161104_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'created', 'ordering': ('date',), 'verbose_name': 'diagram', 'verbose_name_plural': 'diagrams'},
        ),
    ]
