# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0035_auto_20161212_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='num_columns',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
