# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0036_collection_num_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='num_columns',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
