# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0037_auto_20170111_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('name',), 'verbose_name': 'keyword', 'verbose_name_plural': 'keywords'},
        ),
        migrations.AddField(
            model_name='entry',
            name='year_in_school',
            field=models.CharField(choices=[(b'TO', b'Tone Systems'), (b'CO', b'Colour Systems')], default=b'TO', max_length=2),
        ),
    ]
