# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-12 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0038_auto_20170112_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='year_in_school',
            new_name='category',
        ),
    ]
