# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0040_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('-ref',), 'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
