# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0041_auto_20170223_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('ref',), 'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='url1',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url2',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url3',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url4',
        ),
        migrations.AddField(
            model_name='source',
            name='attachment',
            field=models.FilePathField(blank=True, null=True, path=b'/var/www/sound-colour-space.zhdk.ch/pdf', verbose_name='attachment'),
        ),
    ]
