# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0042_auto_20170223_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='attachment',
            field=models.FilePathField(blank=True, max_length=2048, null=True, path=b'/var/www/sound-colour-space.zhdk.ch/pdf', verbose_name='attachment'),
        ),
    ]
