# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0043_auto_20170223_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'created', 'ordering': ('doc_id',), 'verbose_name': 'diagram', 'verbose_name_plural': 'diagrams'},
        ),
        migrations.AlterField(
            model_name='source',
            name='attachment',
            field=models.FilePathField(blank=True, max_length=2048, null=True, path=b'/home/stahl/icst/soundcolourspace/sound-colour-space/website/attachments', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='source',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
