# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-11 17:00
from __future__ import unicode_literals

import common.storage
from django.db import migrations, models
import museum.models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0045_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='image name'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=common.storage.DataStorage(base_url=b'/media/exhibitions/', location=b'/home/stahl/icst/soundcolourspace/sound-colour-space/website/media/exhibitions'), upload_to=museum.models.generate_data_path, verbose_name='cover'),
        ),
    ]
